[package]
name = "shrubman"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.9"
inplace_containers = "0.3.2"
libc = "0.2.178"
log = "0.4.29"
num_enum = "0.7.5"
shared_memory = "0.12.4"
thiserror = "2.0.17"
